---
permalink: deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html 
sidebar: sidebar 
keywords: clean up browser cache 
summary: ONTAP ツールの導入またはアップグレード後にプラグインが自動的に更新されない場合は、ブラウザおよび vCenter Server 上にキャッシュされているダウンロード済みプラグインパッケージをクリーンアップして、 vCenter Server プラグインの問題を解決する必要があります。 
---
= vSphere にキャッシュされているダウンロード済みプラグインパッケージをクリアします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ツールの導入またはアップグレード後にプラグインが自動的に更新されない場合は、ブラウザおよび vCenter Server にキャッシュされているダウンロード済みプラグインパッケージをクリーンアップして、 vCenter Server プラグインの問題を解決する必要があります。

* 手順 *

. 既存のvSphere Web ClientまたはvSphere UIからログアウトします。
. ブラウザキャッシュを削除します。
. vSphere Client にキャッシュされたプラグインパッケージを削除します。vCSAの場合は、次の手順を実行します。
+
.. SSH で VCSA アプライアンスに接続します。
.. VMware vSphere Clientサービスを停止します。
`service-control --stop vsphere-ui`
.. ディレクトリをvCenter Client UI extensionsディレクトリに変更します。 `cd /etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity`
.. を使用して、ネットアップ固有のキャッシュ済みプラグインパッケージを削除します `rm -rf` コマンド：
+
`rm -rf com.netapp.nvpf.webclient-*`

+
`rm -rf com.netapp.vasa.vvol.webclient-*`

+
`rm -rf com.netapp.vsch5-*`

.. VMware vSphere Clientサービスを開始します。
`service-control --start vsphere-ui`



