---
permalink: manage/task_collect_the_log_files.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 用の ONTAP ® ツールのログファイルは、 VSC のグラフィカルユーザインターフェイス（ GUI\ ）のオプションを使用して収集できます。テクニカルサポートに問題のトラブルシューティングを依頼すると、ログファイルの収集を求められることがあります。 
---
= ログファイルを収集します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 用の ONTAP ツールのログファイルは、 VSC のグラフィカルユーザインターフェイス（ GUI ）のオプションを使用して収集できます。テクニカルサポートに問題のトラブルシューティングを依頼すると、ログファイルの収集を求められることがあります。

* このタスクについて *

VASA Provider のログファイルが必要な場合は、 Vendor Provider Control Panel 画面からサポートバンドルを生成できます。このページは VASA Provider のメンテナンスメニューの一部で、仮想アプライアンスのコンソールからアクセスできます。

`\https://vm_ip:9083`


NOTE: Webインターフェイスにアクセスできない場合は、メンテナンスコンソールの*[SSHアクセスの有効化]*オプションを使用します。を参照してください link:../configure/reference_maintenance_console_of_ontap_tools_for_vmware_vsphere.html["ONTAP ツールのメンテナンスコンソールのオプション"]。SSHを有効にすると、SFTPクライアントを使用してONTAP tools for VMware vSphereアプライアンスにアクセスできるようになります。

VSC GUI の「 VSC ログのエクスポート」機能を使用して、 VSC のログファイルを収集できます。VASA Provider を有効にして VSC ログバンドルを収集すると、 VSC ログバンドルに VP ログも含まれるようになります。VSC のログファイルを収集する手順は次のとおりです。

* 手順 *

. ONTAP ツールのホームページで、 * Configuration * > * Export VSC Logs * をクリックします。
+
この処理には数分かかることがあります。

. プロンプトが表示されたら、ローカルコンピュータにファイルを保存します。
+
これで、テクニカルサポートに .zip ファイルを送ることができます。


